apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-aepd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-aepd@sha256:79b70b10cf5ee7dc4d1ff0c2285662236e96f1a15c7f0cfbb9cd65bc85e97457
        name: my-nodejs
        resources: {}
status: {}
